# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18202af460601ea9dbd0b40d0d2254c821e4994b2e72e80154eab71870b6e5b37c7d96af3410017d208671a107171c77a4eb4286b451d370b5364d7e6c20d42c

test:
  secret_key_base: 2bb9edfd17c3fba6500578d0dea078a140cf3f33f00c61c4085811d22e7d04de836587e43114e4393befe37db2daffeecd1ed7224d789cfddb243cea71306a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
